package com.littledoctor.clinicassistant.module.item.acupoint.entity;/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 腧穴表(item_acupoint)
 * 
 * @author 周俊林
 * @version 1.0.0 2020-05-04
 */
@Entity
@Table(name = "item_acupoint")
public class AcupointEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -7553099745124275393L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 品目ID */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "item_id", unique = true, nullable = false, length = 20)
    private Long itemId;

    /** 腧穴名称 */
    @Column(name = "item_name", nullable = false, length = 50)
    private String itemName;

    /** 简拼 */
    @Column(name = "abbr_pinyin", nullable = true, length = 50)
    private String abbrPinyin;

    /** 全拼 */
    @Column(name = "full_pinyin", nullable = true, length = 500)
    private String fullPinyin;

    /** 所属经络 */
    @Column(name = "item_type", nullable = false, length = 10)
    private String itemType;

    /** 定位 */
    @Column(name = "location", nullable = true, length = 500)
    private String location;

    /** 主治 */
    @Column(name = "efficacy", nullable = true, length = 500)
    private String efficacy;

    /** 操作 */
    @Column(name = "operation", nullable = true, length = 100)
    private String operation;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取品目ID
     * 
     * @return 品目ID
     */
    public Long getItemId() {
        return this.itemId;
    }

    /**
     * 设置品目ID
     * 
     * @param itemId
     *          品目ID
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * 获取腧穴名称
     * 
     * @return 腧穴名称
     */
    public String getItemName() {
        return this.itemName;
    }

    /**
     * 设置腧穴名称
     * 
     * @param itemName
     *          腧穴名称
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * 获取简拼
     * 
     * @return 简拼
     */
    public String getAbbrPinyin() {
        return this.abbrPinyin;
    }

    /**
     * 设置简拼
     * 
     * @param abbrPinyin
     *          简拼
     */
    public void setAbbrPinyin(String abbrPinyin) {
        this.abbrPinyin = abbrPinyin;
    }

    /**
     * 获取全拼
     * 
     * @return 全拼
     */
    public String getFullPinyin() {
        return this.fullPinyin;
    }

    /**
     * 设置全拼
     * 
     * @param fullPinyin
     *          全拼
     */
    public void setFullPinyin(String fullPinyin) {
        this.fullPinyin = fullPinyin;
    }

    /**
     * 获取所属经络
     * 
     * @return 所属经络
     */
    public String getItemType() {
        return this.itemType;
    }

    /**
     * 设置所属经络
     * 
     * @param itemType
     *          所属经络
     */
    public void setItemType(String itemType) {
        this.itemType = itemType;
    }

    /**
     * 获取定位
     * 
     * @return 定位
     */
    public String getLocation() {
        return this.location;
    }

    /**
     * 设置定位
     * 
     * @param location
     *          定位
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * 获取主治
     * 
     * @return 主治
     */
    public String getEfficacy() {
        return this.efficacy;
    }

    /**
     * 设置主治
     * 
     * @param efficacy
     *          主治
     */
    public void setEfficacy(String efficacy) {
        this.efficacy = efficacy;
    }

    /**
     * 获取操作
     * 
     * @return 操作
     */
    public String getOperation() {
        return this.operation;
    }

    /**
     * 设置操作
     * 
     * @param operation
     *          操作
     */
    public void setOperation(String operation) {
        this.operation = operation;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}