package com.littledoctor.clinicassistant.module.item.add.entity;/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 品目管理总表(item_all)
 * 
 * @author 周俊林
 * @version 1.0.0 2020-05-04
 */
@Entity
@Table(name = "item_all")
public class ItemAllEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 7651990394774025453L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键ID */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "item_uid", unique = true, nullable = false, length = 20)
    private Long itemUid;

    /** 品目ID */
    @Column(name = "item_id", nullable = false, length = 19)
    private Long itemId;

    /** 品目名称 */
    @Column(name = "item_name", nullable = false, length = 50)
    private String itemName;

    /** 品目分类（1：中草药；2：中成药；3：中药饮片；4：医疗耗材；5：其他耗材；字典键：CGPMFL） */
    @Column(name = "item_type", nullable = false, length = 50)
    private String itemType;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取主键ID
     * 
     * @return 主键ID
     */
    public Long getItemUid() {
        return this.itemUid;
    }

    /**
     * 设置主键ID
     * 
     * @param itemUid
     *          主键ID
     */
    public void setItemUid(Long itemUid) {
        this.itemUid = itemUid;
    }

    /**
     * 获取品目ID
     * 
     * @return 品目ID
     */
    public Long getItemId() {
        return this.itemId;
    }

    /**
     * 设置品目ID
     * 
     * @param itemId
     *          品目ID
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * 获取品目名称
     * 
     * @return 品目名称
     */
    public String getItemName() {
        return this.itemName;
    }

    /**
     * 设置品目名称
     * 
     * @param itemName
     *          品目名称
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * 获取品目分类（1：中草药；2：中成药；3：中药饮片；4：医疗耗材；5：其他耗材；字典键：CGPMFL）
     * 
     * @return 品目分类（1
     */
    public String getItemType() {
        return this.itemType;
    }

    /**
     * 设置品目分类（1：中草药；2：中成药；3：中药饮片；4：医疗耗材；5：其他耗材；字典键：CGPMFL）
     * 
     * @param itemType
     *          品目分类（1
     */
    public void setItemType(String itemType) {
        this.itemType = itemType;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}