package com.littledoctor.clinicassistant.module.purchase.item.entity;/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
import java.math.BigDecimal;
import javax.persistence.*;

/**
 * 品目管理表(item)
 * 
 * @author bianj
 * @version 1.0.0 2020-05-01
 */
@Entity
@Table(name = "item")
public class ItemEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -673153849950521478L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键ID */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "item_id", unique = true, nullable = false, length = 20)
    private Long itemId;

    /** 品目名称 */
    @Column(name = "item_name", nullable = false, length = 50)
    private String itemName;

    /** 品目分类（1：中草药；2：中成药；3：中药饮片；4：医疗耗材；5：其他耗材；字典键：PMFL） */
    @Column(name = "item_type", nullable = false, length = 10)
    private String itemType;

    @Transient
    private String itemTypeName;

    /** 品目小类 */
    @Column(name = "item_small_type", nullable = true, length = 50)
    private String itemSmallType;

    @Transient
    private String itemSmallTypeName;


    /** 条形码 */
    @Column(name = "barcode", nullable = true, length = 50)
    private String barcode;

    /** 简拼 */
    @Column(name = "abbr_pinyin", nullable = true, length = 50)
    private String abbrPinyin;

    /** 全拼 */
    @Column(name = "full_pinyin", nullable = true, length = 500)
    private String fullPinyin;

    /** 方剂出处 */
    @Column(name = "source", nullable = true, length = 50)
    private String source;

    /** 性味归经 */
    @Column(name = "flavor_meridian_tropism", nullable = true, length = 100)
    private String flavorMeridianTropism;

    /** 方剂功用 */
    @Column(name = "function", nullable = true, length = 100)
    private String function;

    /** 功能主治 */
    @Column(name = "efficacy", nullable = true, length = 500)
    private String efficacy;

    /** 成分 */
    @Column(name = "component", nullable = true, length = 500)
    private String component;

    /** 规格 */
    @Column(name = "specifications", nullable = true, length = 100)
    private String specifications;

    /** 用法用量 */
    @Column(name = "usage_dosage", nullable = true, length = 500)
    private String usageDosage;

    /** 方解 */
    @Column(name = "analysis", nullable = true, length = 1000)
    private String analysis;

    /** 方歌 */
    @Column(name = "poem", nullable = true, length = 100)
    private String poem;

    /** 禁忌 */
    @Column(name = "taboo", nullable = true, length = 500)
    private String taboo;

    /** 厂家制造商，产地 */
    @Column(name = "producer", nullable = true, length = 100)
    private String producer;

    /** 是否有毒（1：是；0：否） */
    @Column(name = "is_poison", nullable = true)
    private Integer isPoison;

    /** 进货包装 */
    @Column(name = "pur_unit", nullable = true, length = 10)
    private String purUnit;

    /** 零售单位 */
    @Column(name = "stock_unit", nullable = true, length = 10)
    private String stockUnit;

    /** 单位换算 */
    @Column(name = "unit_convert", nullable = true, length = 10)
    private Long unitConvert;

    /** 库存预警值，保留6位小数可以精确到微克 */
    @Column(name = "stock_warn", nullable = true, length = 16)
    private BigDecimal stockWarn;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取主键ID
     * 
     * @return 主键ID
     */
    public Long getItemId() {
        return this.itemId;
    }

    /**
     * 设置主键ID
     * 
     * @param itemId
     *          主键ID
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * 获取品目名称
     * 
     * @return 品目名称
     */
    public String getItemName() {
        return this.itemName;
    }

    /**
     * 设置品目名称
     * 
     * @param itemName
     *          品目名称
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * 获取品目分类（1：中草药；2：中成药；3：中药饮片；4：医疗耗材；5：其他耗材；字典键：PMFL）
     * 
     * @return 品目分类（1
     */
    public String getItemType() {
        return this.itemType;
    }

    /**
     * 设置品目分类（1：中草药；2：中成药；3：中药饮片；4：医疗耗材；5：其他耗材；字典键：PMFL）
     * 
     * @param itemType
     *          品目分类（1
     */
    public void setItemType(String itemType) {
        this.itemType = itemType;
    }

    /**
     * 获取条形码
     * 
     * @return 条形码
     */
    public String getBarcode() {
        return this.barcode;
    }

    /**
     * 设置条形码
     * 
     * @param barcode
     *          条形码
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    /**
     * 获取简拼
     * 
     * @return 简拼
     */
    public String getAbbrPinyin() {
        return this.abbrPinyin;
    }

    /**
     * 设置简拼
     * 
     * @param abbrPinyin
     *          简拼
     */
    public void setAbbrPinyin(String abbrPinyin) {
        this.abbrPinyin = abbrPinyin;
    }

    /**
     * 获取全拼
     * 
     * @return 全拼
     */
    public String getFullPinyin() {
        return this.fullPinyin;
    }

    /**
     * 设置全拼
     * 
     * @param fullPinyin
     *          全拼
     */
    public void setFullPinyin(String fullPinyin) {
        this.fullPinyin = fullPinyin;
    }

    /**
     * 获取性味归经
     * 
     * @return 性味归经
     */
    public String getFlavorMeridianTropism() {
        return this.flavorMeridianTropism;
    }

    /**
     * 设置性味归经
     * 
     * @param flavorMeridianTropism
     *          性味归经
     */
    public void setFlavorMeridianTropism(String flavorMeridianTropism) {
        this.flavorMeridianTropism = flavorMeridianTropism;
    }

    /**
     * 获取功效，功能主治
     * 
     * @return 功效
     */
    public String getEfficacy() {
        return this.efficacy;
    }

    /**
     * 设置功效，功能主治
     * 
     * @param efficacy
     *          功效
     */
    public void setEfficacy(String efficacy) {
        this.efficacy = efficacy;
    }

    /**
     * 获取成分
     * 
     * @return 成分
     */
    public String getComponent() {
        return this.component;
    }

    /**
     * 设置成分
     * 
     * @param component
     *          成分
     */
    public void setComponent(String component) {
        this.component = component;
    }

    /**
     * 获取规格
     * 
     * @return 规格
     */
    public String getSpecifications() {
        return this.specifications;
    }

    /**
     * 设置规格
     * 
     * @param specifications
     *          规格
     */
    public void setSpecifications(String specifications) {
        this.specifications = specifications;
    }

    /**
     * 获取用法用量
     * 
     * @return 用法用量
     */
    public String getUsageDosage() {
        return this.usageDosage;
    }

    /**
     * 设置用法用量
     * 
     * @param usageDosage
     *          用法用量
     */
    public void setUsageDosage(String usageDosage) {
        this.usageDosage = usageDosage;
    }

    /**
     * 获取禁忌
     * 
     * @return 禁忌
     */
    public String getTaboo() {
        return this.taboo;
    }

    /**
     * 设置禁忌
     * 
     * @param taboo
     *          禁忌
     */
    public void setTaboo(String taboo) {
        this.taboo = taboo;
    }

    /**
     * 获取厂家制造商，产地
     * 
     * @return 厂家制造商
     */
    public String getProducer() {
        return this.producer;
    }

    /**
     * 设置厂家制造商，产地
     * 
     * @param producer
     *          厂家制造商
     */
    public void setProducer(String producer) {
        this.producer = producer;
    }

    /**
     * 获取是否有毒（1：是；0：否）
     * 
     * @return 是否有毒（1
     */
    public Integer getIsPoison() {
        return this.isPoison;
    }

    /**
     * 设置是否有毒（1：是；0：否）
     * 
     * @param isPoison
     *          是否有毒（1
     */
    public void setIsPoison(Integer isPoison) {
        this.isPoison = isPoison;
    }

    /**
     * 获取进货包装
     * 
     * @return 进货包装
     */
    public String getPurUnit() {
        return this.purUnit;
    }

    /**
     * 设置进货包装
     * 
     * @param purUnit
     *          进货包装
     */
    public void setPurUnit(String purUnit) {
        this.purUnit = purUnit;
    }

    /**
     * 获取零售单位
     * 
     * @return 零售单位
     */
    public String getStockUnit() {
        return this.stockUnit;
    }

    /**
     * 设置零售单位
     * 
     * @param stockUnit
     *          零售单位
     */
    public void setStockUnit(String stockUnit) {
        this.stockUnit = stockUnit;
    }

    /**
     * 获取单位换算
     * 
     * @return 单位换算
     */
    public Long getUnitConvert() {
        return this.unitConvert;
    }

    /**
     * 设置单位换算
     * 
     * @param unitConvert
     *          单位换算
     */
    public void setUnitConvert(Long unitConvert) {
        this.unitConvert = unitConvert;
    }

    /**
     * 获取库存预警值，保留6位小数可以精确到微克
     * 
     * @return 库存预警值
     */
    public BigDecimal getStockWarn() {
        return this.stockWarn;
    }

    /**
     * 设置库存预警值，保留6位小数可以精确到微克
     * 
     * @param stockWarn
     *          库存预警值
     */
    public void setStockWarn(BigDecimal stockWarn) {
        this.stockWarn = stockWarn;
    }

    /* This code was generated by TableGo tools, mark 2 end. */

    public String getItemTypeName() {
        return itemTypeName;
    }

    public void setItemTypeName(String itemTypeName) {
        this.itemTypeName = itemTypeName;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getFunction() {
        return function;
    }

    public void setFunction(String function) {
        this.function = function;
    }

    public String getAnalysis() {
        return analysis;
    }

    public void setAnalysis(String analysis) {
        this.analysis = analysis;
    }

    public String getPoem() {
        return poem;
    }

    public void setPoem(String poem) {
        this.poem = poem;
    }

    public String getItemSmallType() {
        return itemSmallType;
    }

    public void setItemSmallType(String itemSmallType) {
        this.itemSmallType = itemSmallType;
    }

    public String getItemSmallTypeName() {
        return itemSmallTypeName;
    }

    public void setItemSmallTypeName(String itemSmallTypeName) {
        this.itemSmallTypeName = itemSmallTypeName;
    }
}