package com.littledoctor.clinicassistant.module.item.skill.entity;/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 医疗项目表(item_skill)
 * 
 * @author 周俊林
 * @version 1.0.0 2020-05-04
 */
@Entity
@Table(name = "item_skill")
public class ItemSkillEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 4626302796042657035L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 品目ID */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "item_id", unique = true, nullable = false, length = 20)
    private Long itemId;

    /** 项目名称 */
    @Column(name = "item_name", nullable = false, length = 50)
    private String itemName;

    /** 简拼 */
    @Column(name = "abbr_pinyin", nullable = true, length = 50)
    private String abbrPinyin;

    /** 全拼 */
    @Column(name = "full_pinyin", nullable = true, length = 500)
    private String fullPinyin;

    /** 单价 */
    @Column(name = "unit_price", nullable = true, length = 12)
    private BigDecimal unitPrice;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取品目ID
     * 
     * @return 品目ID
     */
    public Long getItemId() {
        return this.itemId;
    }

    /**
     * 设置品目ID
     * 
     * @param itemId
     *          品目ID
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * 获取项目名称
     * 
     * @return 项目名称
     */
    public String getItemName() {
        return this.itemName;
    }

    /**
     * 设置项目名称
     * 
     * @param itemName
     *          项目名称
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * 获取简拼
     * 
     * @return 简拼
     */
    public String getAbbrPinyin() {
        return this.abbrPinyin;
    }

    /**
     * 设置简拼
     * 
     * @param abbrPinyin
     *          简拼
     */
    public void setAbbrPinyin(String abbrPinyin) {
        this.abbrPinyin = abbrPinyin;
    }

    /**
     * 获取全拼
     * 
     * @return 全拼
     */
    public String getFullPinyin() {
        return this.fullPinyin;
    }

    /**
     * 设置全拼
     * 
     * @param fullPinyin
     *          全拼
     */
    public void setFullPinyin(String fullPinyin) {
        this.fullPinyin = fullPinyin;
    }

    /**
     * 获取单价
     * 
     * @return 单价
     */
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }

    /**
     * 设置单价
     * 
     * @param unitPrice
     *          单价
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}