package com.littledoctor.clinicassistant.module.item.medicalsupply.entity;/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 医疗用品表(item_medical_supply)
 * 
 * @author 周俊林
 * @version 1.0.0 2020-05-04
 */
@Entity
@Table(name = "item_medical_supply")
public class MedicalSupplyEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -1105398926405982329L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 品目ID */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "item_id", unique = true, nullable = false, length = 20)
    private Long itemId;

    /** 用品名称 */
    @Column(name = "item_name", nullable = false, length = 50)
    private String itemName;

    /** 简拼 */
    @Column(name = "abbr_pinyin", nullable = true, length = 50)
    private String abbrPinyin;

    /** 全拼 */
    @Column(name = "full_pinyin", nullable = true, length = 500)
    private String fullPinyin;

    /** 条形码 */
    @Column(name = "barcode", nullable = true, length = 50)
    private String barcode;

    /** 规格 */
    @Column(name = "specifications", nullable = true, length = 100)
    private String specifications;

    /** 品牌厂家 */
    @Column(name = "producer", nullable = true, length = 100)
    private String producer;

    /** 进货包装 */
    @Column(name = "pur_unit", nullable = true, length = 10)
    private String purUnit;

    /** 零售单位 */
    @Column(name = "stock_unit", nullable = true, length = 10)
    private String stockUnit;

    /** 单位换算 */
    @Column(name = "unit_convert", nullable = true, length = 10)
    private Integer unitConvert;

    /** 库存预警值，保留6位小数可以精确到微克 */
    @Column(name = "stock_warn", nullable = true, length = 16)
    private BigDecimal stockWarn;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取品目ID
     * 
     * @return 品目ID
     */
    public Long getItemId() {
        return this.itemId;
    }

    /**
     * 设置品目ID
     * 
     * @param itemId
     *          品目ID
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * 获取用品名称
     * 
     * @return 用品名称
     */
    public String getItemName() {
        return this.itemName;
    }

    /**
     * 设置用品名称
     * 
     * @param itemName
     *          用品名称
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * 获取简拼
     * 
     * @return 简拼
     */
    public String getAbbrPinyin() {
        return this.abbrPinyin;
    }

    /**
     * 设置简拼
     * 
     * @param abbrPinyin
     *          简拼
     */
    public void setAbbrPinyin(String abbrPinyin) {
        this.abbrPinyin = abbrPinyin;
    }

    /**
     * 获取全拼
     * 
     * @return 全拼
     */
    public String getFullPinyin() {
        return this.fullPinyin;
    }

    /**
     * 设置全拼
     * 
     * @param fullPinyin
     *          全拼
     */
    public void setFullPinyin(String fullPinyin) {
        this.fullPinyin = fullPinyin;
    }

    /**
     * 获取条形码
     * 
     * @return 条形码
     */
    public String getBarcode() {
        return this.barcode;
    }

    /**
     * 设置条形码
     * 
     * @param barcode
     *          条形码
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    /**
     * 获取规格
     * 
     * @return 规格
     */
    public String getSpecifications() {
        return this.specifications;
    }

    /**
     * 设置规格
     * 
     * @param specifications
     *          规格
     */
    public void setSpecifications(String specifications) {
        this.specifications = specifications;
    }

    /**
     * 获取品牌厂家
     * 
     * @return 品牌厂家
     */
    public String getProducer() {
        return this.producer;
    }

    /**
     * 设置品牌厂家
     * 
     * @param producer
     *          品牌厂家
     */
    public void setProducer(String producer) {
        this.producer = producer;
    }

    /**
     * 获取进货包装
     * 
     * @return 进货包装
     */
    public String getPurUnit() {
        return this.purUnit;
    }

    /**
     * 设置进货包装
     * 
     * @param purUnit
     *          进货包装
     */
    public void setPurUnit(String purUnit) {
        this.purUnit = purUnit;
    }

    /**
     * 获取零售单位
     * 
     * @return 零售单位
     */
    public String getStockUnit() {
        return this.stockUnit;
    }

    /**
     * 设置零售单位
     * 
     * @param stockUnit
     *          零售单位
     */
    public void setStockUnit(String stockUnit) {
        this.stockUnit = stockUnit;
    }

    /**
     * 获取单位换算
     * 
     * @return 单位换算
     */
    public Integer getUnitConvert() {
        return this.unitConvert;
    }

    /**
     * 设置单位换算
     * 
     * @param unitConvert
     *          单位换算
     */
    public void setUnitConvert(Integer unitConvert) {
        this.unitConvert = unitConvert;
    }

    /**
     * 获取库存预警值，保留6位小数可以精确到微克
     * 
     * @return 库存预警值
     */
    public BigDecimal getStockWarn() {
        return this.stockWarn;
    }

    /**
     * 设置库存预警值，保留6位小数可以精确到微克
     * 
     * @param stockWarn
     *          库存预警值
     */
    public void setStockWarn(BigDecimal stockWarn) {
        this.stockWarn = stockWarn;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}