package com.littledoctor.clinicassistant.module.item.prescription.entity;/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 方剂表(item_prescription)
 * 
 * @author 周俊林
 * @version 1.0.0 2020-05-04
 */
@Entity
@Table(name = "item_prescription")
public class PrescriptionEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 213924887161256741L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 品目ID */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "item_id", unique = true, nullable = false, length = 20)
    private Long itemId;

    /** 方剂名称 */
    @Column(name = "item_name", nullable = false, length = 50)
    private String itemName;

    /** 简拼 */
    @Column(name = "abbr_pinyin", nullable = true, length = 50)
    private String abbrPinyin;

    /** 全拼 */
    @Column(name = "full_pinyin", nullable = true, length = 500)
    private String fullPinyin;

    /** 条形码 */
    @Column(name = "barcode", nullable = true, length = 50)
    private String barcode;

    /** 方剂分类 */
    @Column(name = "item_type", nullable = true, length = 50)
    private String itemType;

    /** 方剂出处 */
    @Column(name = "source", nullable = true, length = 50)
    private String source;

    /** 组成 */
    @Column(name = "component", nullable = true, length = 500)
    private String component;

    /** 用法用量 */
    @Column(name = "usage_dosage", nullable = true, length = 500)
    private String usageDosage;

    /** 功用 */
    @Column(name = "functions", nullable = true, length = 100)
    private String functions;

    /** 主治 */
    @Column(name = "efficacy", nullable = true, length = 500)
    private String efficacy;

    /** 方解 */
    @Column(name = "analysis", nullable = true, length = 1000)
    private String analysis;

    /** 方歌 */
    @Column(name = "poem", nullable = true, length = 100)
    private String poem;

    /** 禁忌 */
    @Column(name = "taboo", nullable = true, length = 500)
    private String taboo;

    /** 是否有毒（1：是；0：否） */
    @Column(name = "is_poison", nullable = true)
    private Integer isPoison;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取品目ID
     * 
     * @return 品目ID
     */
    public Long getItemId() {
        return this.itemId;
    }

    /**
     * 设置品目ID
     * 
     * @param itemId
     *          品目ID
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * 获取方剂名称
     * 
     * @return 方剂名称
     */
    public String getItemName() {
        return this.itemName;
    }

    /**
     * 设置方剂名称
     * 
     * @param itemName
     *          方剂名称
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * 获取简拼
     * 
     * @return 简拼
     */
    public String getAbbrPinyin() {
        return this.abbrPinyin;
    }

    /**
     * 设置简拼
     * 
     * @param abbrPinyin
     *          简拼
     */
    public void setAbbrPinyin(String abbrPinyin) {
        this.abbrPinyin = abbrPinyin;
    }

    /**
     * 获取全拼
     * 
     * @return 全拼
     */
    public String getFullPinyin() {
        return this.fullPinyin;
    }

    /**
     * 设置全拼
     * 
     * @param fullPinyin
     *          全拼
     */
    public void setFullPinyin(String fullPinyin) {
        this.fullPinyin = fullPinyin;
    }

    /**
     * 获取条形码
     * 
     * @return 条形码
     */
    public String getBarcode() {
        return this.barcode;
    }

    /**
     * 设置条形码
     * 
     * @param barcode
     *          条形码
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    /**
     * 获取方剂分类
     * 
     * @return 方剂分类
     */
    public String getItemType() {
        return this.itemType;
    }

    /**
     * 设置方剂分类
     * 
     * @param itemType
     *          方剂分类
     */
    public void setItemType(String itemType) {
        this.itemType = itemType;
    }

    /**
     * 获取方剂出处
     * 
     * @return 方剂出处
     */
    public String getSource() {
        return this.source;
    }

    /**
     * 设置方剂出处
     * 
     * @param source
     *          方剂出处
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * 获取组成
     * 
     * @return 组成
     */
    public String getComponent() {
        return this.component;
    }

    /**
     * 设置组成
     * 
     * @param component
     *          组成
     */
    public void setComponent(String component) {
        this.component = component;
    }

    /**
     * 获取用法用量
     * 
     * @return 用法用量
     */
    public String getUsageDosage() {
        return this.usageDosage;
    }

    /**
     * 设置用法用量
     * 
     * @param usageDosage
     *          用法用量
     */
    public void setUsageDosage(String usageDosage) {
        this.usageDosage = usageDosage;
    }

    /**
     * 获取功用
     * 
     * @return 功用
     */
    public String getFunctions() {
        return this.functions;
    }

    /**
     * 设置功用
     * 
     * @param functions
     *          功用
     */
    public void setFunctions(String functions) {
        this.functions = functions;
    }

    /**
     * 获取主治
     * 
     * @return 主治
     */
    public String getEfficacy() {
        return this.efficacy;
    }

    /**
     * 设置主治
     * 
     * @param efficacy
     *          主治
     */
    public void setEfficacy(String efficacy) {
        this.efficacy = efficacy;
    }

    /**
     * 获取方解
     * 
     * @return 方解
     */
    public String getAnalysis() {
        return this.analysis;
    }

    /**
     * 设置方解
     * 
     * @param analysis
     *          方解
     */
    public void setAnalysis(String analysis) {
        this.analysis = analysis;
    }

    /**
     * 获取方歌
     * 
     * @return 方歌
     */
    public String getPoem() {
        return this.poem;
    }

    /**
     * 设置方歌
     * 
     * @param poem
     *          方歌
     */
    public void setPoem(String poem) {
        this.poem = poem;
    }

    /**
     * 获取禁忌
     * 
     * @return 禁忌
     */
    public String getTaboo() {
        return this.taboo;
    }

    /**
     * 设置禁忌
     * 
     * @param taboo
     *          禁忌
     */
    public void setTaboo(String taboo) {
        this.taboo = taboo;
    }

    /**
     * 获取是否有毒（1：是；0：否）
     * 
     * @return 是否有毒（1
     */
    public Integer getIsPoison() {
        return this.isPoison;
    }

    /**
     * 设置是否有毒（1：是；0：否）
     * 
     * @param isPoison
     *          是否有毒（1
     */
    public void setIsPoison(Integer isPoison) {
        this.isPoison = isPoison;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}