package com.littledoctor.clinicassistant.module.rxdaily.entity;

import javax.persistence.*;

import org.hibernate.annotations.GenericGenerator;

/**
 * 医技处方(RX_DAILY_SKILL)
 * 
 * @author bianj
 * @version 1.0.0 2021-03-03
 */
@Entity
@Table(name = "RX_DAILY_SKILL")
public class RxDailySkill implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -8770242171140704584L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 虚拟主键 */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "RX_DAILY_ID_SKILL_ID", unique = true, nullable = false, length = 20)
    private Long rxDailyIdSkillId;

    /** rxDailyId */
    @Column(name = "RX_DAILY_ID", nullable = false, length = 19)
    private Long rxDailyId;

    /** 治疗次数 */
    @Column(name = "DOSE_COUNT", nullable = true, length = 10)
    private Long doseCount;

    /** 单次金额 */
    @Column(name = "SINGLE_MONEY", nullable = true, length = 12)
    private String singleMoney;

    /** 总金额 */
    @Column(name = "TOTAL_MONEY", nullable = true, length = 12)
    private String totalMoney;

    /** 医嘱 */
    @Column(name = "ADVICE", nullable = true, length = 100)
    private String advice;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取虚拟主键
     * 
     * @return 虚拟主键
     */
    public Long getRxDailyIdSkillId() {
        return this.rxDailyIdSkillId;
    }

    /**
     * 设置虚拟主键
     * 
     * @param rxDailyIdSkillId
     *          虚拟主键
     */
    public void setRxDailyIdSkillId(Long rxDailyIdSkillId) {
        this.rxDailyIdSkillId = rxDailyIdSkillId;
    }

    /**
     * 获取rxDailyId
     * 
     * @return rxDailyId
     */
    public Long getRxDailyId() {
        return this.rxDailyId;
    }

    /**
     * 设置rxDailyId
     * 
     * @param rxDailyId
     */
    public void setRxDailyId(Long rxDailyId) {
        this.rxDailyId = rxDailyId;
    }

    /**
     * 获取治疗次数
     * 
     * @return 治疗次数
     */
    public Long getDoseCount() {
        return this.doseCount;
    }

    /**
     * 设置治疗次数
     * 
     * @param doseCount
     *          治疗次数
     */
    public void setDoseCount(Long doseCount) {
        this.doseCount = doseCount;
    }

    /**
     * 获取单次金额
     * 
     * @return 单次金额
     */
    public String getSingleMoney() {
        return this.singleMoney;
    }

    /**
     * 设置单次金额
     * 
     * @param singleMoney
     *          单次金额
     */
    public void setSingleMoney(String singleMoney) {
        this.singleMoney = singleMoney;
    }

    /**
     * 获取总金额
     * 
     * @return 总金额
     */
    public String getTotalMoney() {
        return this.totalMoney;
    }

    /**
     * 设置总金额
     * 
     * @param totalMoney
     *          总金额
     */
    public void setTotalMoney(String totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * 获取医嘱
     * 
     * @return 医嘱
     */
    public String getAdvice() {
        return this.advice;
    }

    /**
     * 设置医嘱
     * 
     * @param advice
     *          医嘱
     */
    public void setAdvice(String advice) {
        this.advice = advice;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}