package com.littledoctor.clinicassistant.module.rxdaily.entity;

import java.math.BigDecimal;
import javax.persistence.*;

import org.hibernate.annotations.GenericGenerator;

/**
 * 中成药处方(RX_DAILY_PATENT)
 * 
 * @author bianj
 * @version 1.0.0 2021-03-03
 */
@Entity
@Table(name = "RX_DAILY_PATENT")
public class RxDailyPatent implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 7301793576198438387L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 虚拟主键 */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "RX_DAILY_PATENT_ID", unique = true, nullable = false, length = 20)
    private Long rxDailyPatentId;

    /** 处方笺ID */
    @Column(name = "RX_DAILY_ID", nullable = false, length = 19)
    private Long rxDailyId;

    /** 总金额 */
    @Column(name = "TOTAL_MONEY", nullable = true, length = 12)
    private BigDecimal totalMoney;

    /** 医嘱 */
    @Column(name = "ADVICE", nullable = true, length = 100)
    private String advice;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取虚拟主键
     * 
     * @return 虚拟主键
     */
    public Long getRxDailyPatentId() {
        return this.rxDailyPatentId;
    }

    /**
     * 设置虚拟主键
     * 
     * @param rxDailyPatentId
     *          虚拟主键
     */
    public void setRxDailyPatentId(Long rxDailyPatentId) {
        this.rxDailyPatentId = rxDailyPatentId;
    }

    /**
     * 获取处方笺ID
     * 
     * @return 处方笺ID
     */
    public Long getRxDailyId() {
        return this.rxDailyId;
    }

    /**
     * 设置处方笺ID
     * 
     * @param rxDailyId
     *          处方笺ID
     */
    public void setRxDailyId(Long rxDailyId) {
        this.rxDailyId = rxDailyId;
    }

    /**
     * 获取总金额
     * 
     * @return 总金额
     */
    public BigDecimal getTotalMoney() {
        return this.totalMoney;
    }

    /**
     * 设置总金额
     * 
     * @param totalMoney
     *          总金额
     */
    public void setTotalMoney(BigDecimal totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * 获取医嘱
     * 
     * @return 医嘱
     */
    public String getAdvice() {
        return this.advice;
    }

    /**
     * 设置医嘱
     * 
     * @param advice
     *          医嘱
     */
    public void setAdvice(String advice) {
        this.advice = advice;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}