package com.littledoctor.clinicassistant.module.rxdaily.entity;/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.0.0
 */
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

/**
 * 结算表(SETTLE_ACCOUNT)
 * 
 * @author bianj
 * @version 1.0.0 2019-11-02
 */
@Entity
@Table(name = "SETTLE_ACCOUNT")
public class SettleAccount implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 8990811561258347718L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键ID */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "SETTLE_ACCOUNT_ID", unique = true, nullable = false, length = 20)
    private Long settleAccountId;

    /** 病历ID */
    @Column(name = "RECORD_ID", nullable = false, length = 20)
    private Long recordId;

    /** 会员卡号 */
    @Column(name = "VIP_CARD_NUMBER", nullable = true, length = 15)
    private String vipCardNumber;

    /** 应收 */
    @Column(name = "RECEIVABLE", nullable = true, length = 12)
    private BigDecimal receivable;

    /** 折扣 */
    @Column(name = "DISCOUNT", nullable = true, length = 2)
    private BigDecimal discount;

    /** 实收 */
    @Column(name = "ACTUAL_RECEIVABLE", nullable = true, length = 12)
    private BigDecimal actualReceivable;

    /** 找零 */
    @Column(name = "GIVE_CHANGE", nullable = true, length = 12)
    private BigDecimal giveChange;

    /** 支付方式 */
    @Column(name = "PAYMENT_TYPE", nullable = true)
    private Integer paymentType;

    /** 支付状态 1：未支付 2：已支付*/
    @Column(name = "PAYMENT_STATE", nullable = true)
    private Integer paymentState;

    /** 支付时间 */
    @Column(name = "PAYMENT_TIME", nullable = true)
    private Date paymentTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取主键ID
     * 
     * @return 主键ID
     */
    public Long getSettleAccountId() {
        return this.settleAccountId;
    }

    /**
     * 设置主键ID
     * 
     * @param settleAccountId
     *          主键ID
     */
    public void setSettleAccountId(Long settleAccountId) {
        this.settleAccountId = settleAccountId;
    }

    /**
     * 获取病历ID
     * 
     * @return 病历ID
     */
    public Long getRecordId() {
        return this.recordId;
    }

    /**
     * 设置病历ID
     * 
     * @param recordId
     *          病历ID
     */
    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    /**
     * 获取会员卡号
     * 
     * @return 会员卡号
     */
    public String getVipCardNumber() {
        return this.vipCardNumber;
    }

    /**
     * 设置会员卡号
     * 
     * @param vipCardNumber
     *          会员卡号
     */
    public void setVipCardNumber(String vipCardNumber) {
        this.vipCardNumber = vipCardNumber;
    }

    /**
     * 获取应收
     * 
     * @return 应收
     */
    public BigDecimal getReceivable() {
        return this.receivable;
    }

    /**
     * 设置应收
     * 
     * @param receivable
     *          应收
     */
    public void setReceivable(BigDecimal receivable) {
        this.receivable = receivable;
    }

    /**
     * 获取折扣
     * 
     * @return 折扣
     */
    public BigDecimal getDiscount() {
        return this.discount;
    }

    /**
     * 设置折扣
     * 
     * @param discount
     *          折扣
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * 获取实收
     * 
     * @return 实收
     */
    public BigDecimal getActualReceivable() {
        return this.actualReceivable;
    }

    /**
     * 设置实收
     * 
     * @param actualReceivable
     *          实收
     */
    public void setActualReceivable(BigDecimal actualReceivable) {
        this.actualReceivable = actualReceivable;
    }

    /**
     * 获取找零
     * 
     * @return 找零
     */
    public BigDecimal getGiveChange() {
        return this.giveChange;
    }

    /**
     * 设置找零
     * 
     * @param giveChange
     *          找零
     */
    public void setGiveChange(BigDecimal giveChange) {
        this.giveChange = giveChange;
    }

    /**
     * 获取支付方式
     * 
     * @return 支付方式
     */
    public Integer getPaymentType() {
        return this.paymentType;
    }

    /**
     * 设置支付方式
     * 
     * @param paymentType
     *          支付方式
     */
    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * 获取支付状态
     * 
     * @return 支付状态
     */
    public Integer getPaymentState() {
        return this.paymentState;
    }

    /**
     * 设置支付状态
     * 
     * @param paymentState
     *          支付状态
     */
    public void setPaymentState(Integer paymentState) {
        this.paymentState = paymentState;
    }

    /**
     * 获取支付时间
     * 
     * @return 支付时间
     */
    public Date getPaymentTime() {
        return this.paymentTime;
    }

    /**
     * 设置支付时间
     * 
     * @param paymentTime
     *          支付时间
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}