package com.littledoctor.clinicassistant.module.system.menu.entity;

import java.math.BigDecimal;
import javax.persistence.*;

import org.hibernate.annotations.GenericGenerator;

/**
 * SYS_MENU
 * 
 * @author bianj
 * @version 1.0.0 2019-11-17
 */
@Entity
@Table(name = "SYS_MENU")
public class MenuEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -6126046107365207741L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键ID */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "MENU_ID", unique = true, nullable = false, length = 20)
    private Long menuId;

    /** 父级菜单ID */
    @Column(name = "PARENT_MENU_ID", nullable = false, length = 20)
    private Long parentMenuId;

    /** 菜单名称 */
    @Column(name = "MENU_NAME", nullable = false, length = 50)
    private String menuName;

    /** 菜单URL */
    @Column(name = "MENU_URL", nullable = true, length = 255)
    private String menuUrl;

    /** 菜单图标 */
    @Column(name = "MENU_ICON", nullable = true, length = 50)
    private String menuIcon;

    /** 菜单顺序号 */
    @Column(name = "MENU_ORDER", nullable = true, length = 10)
    private BigDecimal menuOrder;

    /** 是否有效 */
    @Column(name = "IS_VALID", nullable = false)
    private Integer isValid;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取主键ID
     * 
     * @return 主键ID
     */
    public Long getMenuId() {
        return this.menuId;
    }

    /**
     * 设置主键ID
     * 
     * @param menuId
     *          主键ID
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * 获取父级菜单ID
     * 
     * @return 父级菜单ID
     */
    public Long getParentMenuId() {
        return this.parentMenuId;
    }

    /**
     * 设置父级菜单ID
     * 
     * @param parentMenuId
     *          父级菜单ID
     */
    public void setParentMenuId(Long parentMenuId) {
        this.parentMenuId = parentMenuId;
    }

    /**
     * 获取菜单名称
     * 
     * @return 菜单名称
     */
    public String getMenuName() {
        return this.menuName;
    }

    /**
     * 设置菜单名称
     * 
     * @param menuName
     *          菜单名称
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * 获取菜单URL
     * 
     * @return 菜单URL
     */
    public String getMenuUrl() {
        return this.menuUrl;
    }

    /**
     * 设置菜单URL
     * 
     * @param menuUrl
     *          菜单URL
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }

    public String getMenuIcon() {
        return menuIcon;
    }

    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon;
    }

    /**
     * 获取菜单顺序号
     * 
     * @return 菜单顺序号
     */
    public BigDecimal getMenuOrder() {
        return this.menuOrder;
    }

    /**
     * 设置菜单顺序号
     * 
     * @param menuOrder
     *          菜单顺序号
     */
    public void setMenuOrder(BigDecimal menuOrder) {
        this.menuOrder = menuOrder;
    }

    /**
     * 获取是否有效
     * 
     * @return 是否有效
     */
    public Integer getIsValid() {
        return this.isValid;
    }

    /**
     * 设置是否有效
     * 
     * @param isValid
     *          是否有效
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}