package com.littledoctor.clinicassistant.module.item.meridian.entity;/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 经络表(item_meridian)
 * 
 * @author 周俊林
 * @version 1.0.0 2020-05-04
 */
@Entity
@Table(name = "item_meridian")
public class MeridianEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -4450306334689067936L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 品目ID */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "item_id", unique = true, nullable = false, length = 20)
    private Long itemId;

    /** 经络名称 */
    @Column(name = "item_name", nullable = false, length = 50)
    private String itemName;

    /** 简拼 */
    @Column(name = "abbr_pinyin", nullable = true, length = 50)
    private String abbrPinyin;

    /** 全拼 */
    @Column(name = "full_pinyin", nullable = true, length = 500)
    private String fullPinyin;

    /** 经络分类 */
    @Column(name = "item_type", nullable = false, length = 10)
    private String itemType;

    /** 循行部位 */
    @Column(name = "circulation_route", nullable = true, length = 1000)
    private String circulationRoute;

    /** 基本功能 */
    @Column(name = "functions", nullable = true, length = 500)
    private String functions;

    /** 原文（灵枢经脉） */
    @Column(name = "original_text", nullable = true, length = 500)
    private String originalText;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取品目ID
     * 
     * @return 品目ID
     */
    public Long getItemId() {
        return this.itemId;
    }

    /**
     * 设置品目ID
     * 
     * @param itemId
     *          品目ID
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * 获取经络名称
     * 
     * @return 经络名称
     */
    public String getItemName() {
        return this.itemName;
    }

    /**
     * 设置经络名称
     * 
     * @param itemName
     *          经络名称
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * 获取简拼
     * 
     * @return 简拼
     */
    public String getAbbrPinyin() {
        return this.abbrPinyin;
    }

    /**
     * 设置简拼
     * 
     * @param abbrPinyin
     *          简拼
     */
    public void setAbbrPinyin(String abbrPinyin) {
        this.abbrPinyin = abbrPinyin;
    }

    /**
     * 获取全拼
     * 
     * @return 全拼
     */
    public String getFullPinyin() {
        return this.fullPinyin;
    }

    /**
     * 设置全拼
     * 
     * @param fullPinyin
     *          全拼
     */
    public void setFullPinyin(String fullPinyin) {
        this.fullPinyin = fullPinyin;
    }

    /**
     * 获取经络分类
     * 
     * @return 经络分类
     */
    public String getItemType() {
        return this.itemType;
    }

    /**
     * 设置经络分类
     * 
     * @param itemType
     *          经络分类
     */
    public void setItemType(String itemType) {
        this.itemType = itemType;
    }

    /**
     * 获取循行部位
     * 
     * @return 循行部位
     */
    public String getCirculationRoute() {
        return this.circulationRoute;
    }

    /**
     * 设置循行部位
     * 
     * @param circulationRoute
     *          循行部位
     */
    public void setCirculationRoute(String circulationRoute) {
        this.circulationRoute = circulationRoute;
    }

    /**
     * 获取基本功能
     * 
     * @return 基本功能
     */
    public String getFunctions() {
        return this.functions;
    }

    /**
     * 设置基本功能
     * 
     * @param functions
     *          基本功能
     */
    public void setFunctions(String functions) {
        this.functions = functions;
    }

    /**
     * 获取原文（灵枢经脉）
     * 
     * @return 原文（灵枢经脉）
     */
    public String getOriginalText() {
        return this.originalText;
    }

    /**
     * 设置原文（灵枢经脉）
     * 
     * @param originalText
     *          原文（灵枢经脉）
     */
    public void setOriginalText(String originalText) {
        this.originalText = originalText;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}